### ISSUE TITLE
None-Type's and 630's at login

### ISSUE THREAD

**Issue by AmericanEnglish** [cyberkitsune/PSO2Proxy#121]
Upon First login users are 630'd and then are able to login upon the second login are allowed on. New None-Type users are generated. As seen in the images
![problem2](https://cloud.githubusercontent.com/assets/9370077/5156731/0b0e2e74-72aa-11e4-93eb-bfef1d968142.png)

**Comment by kamijoutouma** [comment]
@cyberkitsune I will look into this and try to find why this is happening 
I will comment again if i find anything

**Comment by AmericanEnglish** [comment]
When this happened it happened most during the "feed" (the hash value) update. I had to dial the server back to a previous version. Although it does STILL happen i noticed it most when Linode was being DDoS'ed. When people try to connect it would register them as connected but their PID would be empty similar to this.  Very rarely i do notice the server will say that more people are connected than are actually connected such as "6 people connected" but it only prints 5. I assume this is the same thing?

So replication i say would be super difficult unless you want to dial a server back to the feed update where it happened the most frequently.

**Comment by kamijoutouma** [comment]
hmm let me know when it happens again and i will look into it again for now i have found nothing
