### ISSUE TITLE
Adding install instructions for certain plugins

### ISSUE THREAD

**Issue by flyergo** [cyberkitsune/PSO2Proxy#139]
I just enabled the Translation plugin for my proxy by symlink-ing it.
But it didn't work at first because i didn't install the **unicodescript** and **goslate** libs. 

[And it seems i wasn't the only one with these kind of problems.](http://www.pso-world.com/forums/showthread.php?t=222144)

I solved my problem in the end by doing the following:

<code>
apt-get install python-pip | pip install unicodescript | pip install goslate
</code>

Maybe we should add those to the Readme.md or at least mention somewhere that certain plugins require more python libs and howto install those.

**Comment by acffordyce973** [comment]
Instructions are already available in the Wiki: https://github.com/cyberkitsune/PSO2Proxy/wiki/Enabling-Proxy-end-Translations

**Comment by flyergo** [comment]
Oh I see. I didn't take a look into the wiki, yesterday. My bad then.

Thanks for 2bfa8b2c5a6e4f361aa938f5d81af7cb73d5124e. 

This might help others, too.
