### ISSUE TITLE
Users can't log in if environment running the proxy doesn't support UTF-8

### ISSUE THREAD

**Issue by nixxquality** [cyberkitsune/PSO2Proxy#141]
```python
            print("[ShipProxy] Found address %s for port %i, named %s" % (
                blocks.blockList[port][0], port, blocks.blockList[port][1]))
```
[proxy/ShipProxy.py](https://github.com/cyberkitsune/PSO2Proxy/blob/master/proxy/ShipProxy.py#L188-L189)

I had some issues with my locale settings where UTF-8 wasn't enabled properly, so whenever someone tried to connect this print command failed (UnicodeEndodeError) and they got disconnected.
The solution was simply to fix my LC_ environment variables, but it seems pretty dumb that logging failing can cause disconnects.

You should probably wrap it in a try: block or something.

*Note that the system supports UTF-8 but my tty settings couldn't handle utf-8 characters being printed.*

**Comment by cyberkitsune** [comment]
Fixed this in 05ab244aa5205ceba6c4eb03becb8d8e5743fe43
