### ISSUE TITLE
Error 630 when changing to vita blocks

### ISSUE THREAD

**Issue by yucachaaaan** [cyberkitsune/PSO2Proxy#150]
![ss 2015-03-25 at 10 20 52](https://cloud.githubusercontent.com/assets/5484761/6826564/4ffee4bc-d33d-11e4-95cc-aeadf0b23ab0.png)

I am able to login with my credentials and got into any block. However, when attempting to change blocks, I get an Error 630. Tried deleting blocknames.resources.json and it still happened.

A friend of mine is able to change blocks, and he didn't pull the latest version (last pull was last week according to him) and he got the blocknames.resources.json deleted as well.

Server is running Debian 7 x86, also compiled all dependencies from source.

**Comment by acffordyce973** [comment]
Confirming an issue changing to Vita blocks (tested on the public proxy). @cyberkitsune you might want to check this out.

**Comment by flyergo** [comment]
Also block translation doesn't seem to work for block others than your own. 
Might be related.
![blocktranslations](https://cloud.githubusercontent.com/assets/10029199/6837110/fb620cf2-d348-11e4-8ee3-fa2a379b794e.png)

**Comment by cyberkitsune** [comment]
@flyergo for the record, that also was caused by the same bug :)

**Comment by flyergo** [comment]
@cyberkitsune when I first saw it I already thought that is weird... and since everything else seemed to work I didn't open a bug for it. Then somebody on my team said he always gets disconnected if he changes to vita blocks, then it came to me. And that's about the time when you noticed it. =)

**Comment by alama** [comment]
Yes, also noticed switching to VIta blocks with a local proxy results in a 630 error, and the server is at 7319380

**Comment by yucachaaaan** [comment]
Okay, seems that after Episode 4, the issue persists (even after downloading the SEGA keys from IRC, pulled the latest version). Happens on every block, and my team mate also has the same problem.

**Comment by acffordyce973** [comment]
You mean that the issue has returned. Will check and confirm or not.

**Comment by acffordyce973** [comment]
Unable to reproduce on the public proxy. Tried most of the Vita blocks and block change is fine. Sounds like an issue with your configuration.

**Comment by yucachaaaan** [comment]
Seems like it. I didn't reboot when I updated the server for a long time, so something might have caused from that. Works fine now.
