### ISSUE TITLE
ChatTranslator.py plugin not working on Shared Ship

### ISSUE THREAD

**Issue by kamijoutouma** [cyberkitsune/PSO2Proxy#152]
http://pastebin.com/LT7caxmZ

http://pastebin.com/VBS93Gyr (full log)

the main issue is that the translation is failing because it's 503'ing meaning it's timing out

any idea what could be causing this?

- [x]  find reason for issues with translation of chat messages (https://github.com/cyberkitsune/PSO2Proxy/issues/151 - similar but yeah these errors might be the cause)

~~an unhandled error (will look into)~~ caused by dead irc server

**Comment by kamijoutouma** [comment]
goslate updated

To fix said issue just type this
```
sudo pip install --update unicodescript microsofttranslator goslate
```

**Comment by kamijoutouma** [comment]
@cyberkitsune recommend updating goslate on public server

**Comment by kamijoutouma** [comment]
G-11 or the shared server incoming messages are not translated but outgoing ones are 
However there are no 503's?
should probably add the shared server to the list of servers +1

**Comment by TheCrimsonDevil** [comment]
I attempted to update the packages, but it looks like I don't have sudo access. Will poke CK about this. Thanks!

**Comment by kamijoutouma** [comment]
@TheCrimsonDevil @cyberkitsune will verbose to see if incoming packet is different on shared ship

**Comment by acffordyce973** [comment]
This has been an issue since Challenge mode and shared ships were released. @cyberkitsune might want to look into it when able.

**Comment by kamijoutouma** [comment]
I have provided acf alam_squeeze cyberkitsune and aida with my packets from the packet logger in a zip file in irc

Also it appears that party member incoming messages are translated on shared ship. However non party member messages are not.

Also if possible I think private messages should be translated too

**Comment by cyberkitsune** [comment]
Can't reproduce with current version of PSO2Proxy and modules.

**Comment by kamijoutouma** [comment]
You can reproduce this by going into a quest on the shared ship. Japanese characters are not translated there.
They are however translated in lobby now :).

**Comment by kamijoutouma** [comment]
http://i.imgur.com/l3wx9zi.jpg
http://i.imgur.com/Sx6iK0N.jpg

**Comment by kamijoutouma** [comment]
Did some testing. Turns out sega uses the team chat packet on shared ship for messages sent from people not in your party that are in quest with you.

Thanks sega :|

**Comment by kamijoutouma** [comment]
would be nice if this could be reopened.
