### ISSUE TITLE
Error 630 on Featured Quest block, Time Attacks block, and leaving Shared Ship

### ISSUE THREAD

**Issue by Norenia** [cyberkitsune/PSO2Proxy#155]
Possible that leaving Shared Ship ended up directing me to one of those two blocks without my input. After the error takes me back to the ship screen, I am unable to log in again. After shutting down the game and restarting, it is still unable to connect once, but finally connects after that.

**Comment by alama** [comment]
I said, up the timeout on the sockets, maybe?

And this issue not only affecting the public proxy, private ones as well, I had to retry 27 times to connect with my own proxy....

`[-] Timing out client: IPv4Address(TCP, '###.###.###.###', #####)`

`[-] Unhandled Error
	Traceback (most recent call last):
	Failure: twisted.internet.error.TimeoutError: User timeout caused connection failure.`

**Comment by cyberkitsune** [comment]
It could be because of port issues too; SEGA could be finally assigning blocks no non unique ports.

**Comment by alama** [comment]
change 17b6a46 should help, making the timeout be done by the game servers, not by the proxy

**Comment by tessar9070** [comment]
it's proxy
try copy pate's proxy

2015-08-30 6:04 GMT+07:00 Alam Arias <notifications@github.com>:

**Comment by tessar9070** [comment]
use vpngate existing in-world pso2 forum
or doing manual proxy on a network machine

2015-10-28 15:59 GMT+07:00 acffordyce973 <notifications@github.com>:
