### ISSUE TITLE
Team chat translated packet might not be formatted correctly

### ISSUE THREAD

**Issue by kamijoutouma** [cyberkitsune/PSO2Proxy#165]
http://imgur.com/B7Eya1g,QmjZDZX,5uIffYv

Pretty sure everyone in team chat can see the message though as they responded the first time i posted it before i decided to take a screenshot.

Further Testing should be done.

**Comment by cyberkitsune** [comment]
Team chat does not support translation.

**Comment by kamijoutouma** [comment]
Are you sure because when i post messages in the team chat it translates them. The shared ship works properly now so there could be an issue in the code thats not telling it that i'm not on the shared ship.

@cyberkitsune

**Comment by kamijoutouma** [comment]
Public proxy still needs to be restarted at some point and alam fixed my private proxy.
