### ISSUE TITLE
Need help !

### ISSUE THREAD

**Issue by StormX0** [cyberkitsune/PSO2Proxy#172]
I had download Pso 2 Tweaker last week. When i login game and create character then i press play. the loading screen appear but the game has stuck in that.

I set proxy, run troubleshooting, update game, uninstall and reinstall game but not change.

Please help me guy !

Sorry, my english isn't good

**Comment by acffordyce973** [comment]
Corrupted game client issue, not an issue with the proxy code.

Possible fix: Open PSO2 Tweaker > Orb Menu at the top left > Troubleshooting menu > Check for Old/Missing Files > Launch the game without any English patches to test.

If that doesn't work then join our support room using the information here https://github.com/cyberkitsune/PSO2Proxy/wiki/Troubleshooting#irc-support

**Comment by tessar9070** [comment]
me to it's not work
so ???

2015-10-24 18:42 GMT+07:00 acffordyce973 <notifications@github.com>:

**Comment by tessar9070** [comment]
I was overcome with reinstall my PC and could eventually
and sorry I translate through google translation
-_-Leo-_-

2015-10-27 21:41 GMT+07:00 arga tessar <salah.tessar@gmail.com>:
