### ISSUE TITLE
[Request] Something about logged in logged out for proxy users

### ISSUE THREAD

**Issue by EXOxNet** [cyberkitsune/PSO2Proxy#175]
Excuse me, i wanna request something about pso2proxy feature/plugin.

Feature/plugin: logged in and logged out for all proxy user inside proxy through System Chat.
Using player name,
i.e. : [Proxy] %PlayerName% has logged in. / [Proxy] %PlayerName% has logged out.

Sorry if wrong session/place.
Thanks.

**Comment by acffordyce973** [comment]
I seriously doubt that PSO2Proxy Public users are going to want to know when someone logs in or out. It would create too much spam on the public server and should really stay like the game designed it, for friends only. It would work for private servers though.
