### ISSUE TITLE
Proxy Usage for SEA?

### ISSUE THREAD

**Issue by lifeiscontent** [cyberkitsune/PSO2Proxy#176]
Hi there, I noticed PlayPark has a PSO2 English Client and was wondering if your proxy services work with the SEA servers?

If so, how do I set that up?

**Comment by acffordyce973** [comment]
The proxy will not work with SEA in its current form, and we won't support it ourselves. Someone would need to fork the project and make the changes themselves.
See here: https://github.com/cyberkitsune/PSO2Proxy/wiki/Troubleshooting#please-note

**Comment by lifeiscontent** [comment]
@acffordyce973 thanks for the info, is the reason being that the client is vastly different? or would I effectively just have to create a private proxy and run it through the different IPs of SEA?

**Comment by acffordyce973** [comment]
Yea, the packets for the SEA client are different. Simply changing the IPs would probably be enough to show the ships as online but nothing else would work.

**Comment by cyberkitsune** [comment]
@lifeiscontent the primary reason is that I do not wish to support asiasoft or the SEA version of PSO2. The game is behind in updates by a large amount, the localization is terrible and inaccurate, the asiasoft is milking the game to be pay to win.

From a technical standpoint there would be only little modifications needed to make it work (mostly packet padding changes) but I don't wish to support it myself. As previously mentioned you're very welcome to fork and make the changes yourself. PSO2Proxy is open source after all.

**Comment by lifeiscontent** [comment]
@cyberkitsune I see, thank you very much for the info. I think I'll continue playing the JP version you have made very good points and I agree with them :)
