### ISSUE TITLE
Trying to enabling Translator.py but got error

### ISSUE THREAD

**Issue by EXOxNet** [cyberkitsune/PSO2Proxy#177]
As i say in title issue.

what i got :
```
[ShipProxy] Importing plugins.Translate...
Traceback (most recent call last):
  File "./PSO2Proxy.py", line 144, in <module>
    main()
  File "./PSO2Proxy.py", line 128, in main
    __import__(plug)
  File "/root/PSO2Proxy/proxy/plugins/Translate.py", line 10, in <module>
    from unicodescript import script
ImportError: No module named unicodescript
```

what i do:
I try this on new VPS, clone this github, set "myIpAddr" from my VPS's IP, using newest sega key, create my private / public keypair, make translator.py symlinks, start up the server, and got this error.

Attached Image :
![untitled](https://cloud.githubusercontent.com/assets/16914200/13067877/ebd2ba3c-d4a7-11e5-8e37-9c03e5c7275b.jpg)

**Comment by alama** [comment]
What is so hard on reading the [Wiki about the Translations plugin?](https://github.com/cyberkitsune/PSO2Proxy/wiki/Enabling-Proxy-end-Translations)

**Comment by alama** [comment]
Just to note: you need a [paid Google account](https://cloud.google.com/translate/v2/pricing) or sign for a MS Azure account and have [free 2M chars/month](https://www.microsoft.com/en-us/translator/getstarted.aspx), you will need to add the API key into the translation config file

**Comment by EXOxNet** [comment]
In MS Azure...
I have trouble in "Register your application"
where in the :
-Client ID
-Redirect URI
-Enable/Disable subdomain access?

**Comment by alama** [comment]
what so hard of thinking for yourself?
Client ID: just give the name of the Proxy, for my exp, I will name it "MyClientID"
Name: PSO2Proxy
Client secret: Save this secret for later, for my exp, I have it "MyClientsecret"
Redirect URI: you are not being using the BING API for consent flow (Web site usage), just give any vaild URL, anything will do
Enable/Disable subdomain access: again,for using for consent flow, this option does not matter

now in proxy/cfg/translator.config.yml, you should have the following stuff
`{msTranslateID: MyClientID, msTranslateSecret: MyClientsecret,
  translationService: 0}`

**Comment by EXOxNet** [comment]
Ok, thanks for helping.
