### ISSUE TITLE
Cannot uninstall PSO2Proxy

### ISSUE THREAD

**Issue by sukuraumono** [cyberkitsune/PSO2Proxy#184]
Because I want to uninstall PSO2Proxy, I removed "publickey.blob", "ddraw.dll", "rsainject.dll" from bin folder. But this didn't work and got warning

 "PSO2Proxy: Either PSO2Proxy is not configured correctly on your computer or you are trying to connect using a PS4 console.".

So, I uninstalled whole PSO2 and reinstalled it. But somehow, i got same warning.
How should I uninstall PSO2Proxy correctly?

**Comment by acffordyce973** [comment]
You don't 'uninstall' PSO2Proxy.

If you're using the Tweaker then:
Orb Menu > Other Tasks > Revert PSO2Proxy Settings to JP.

If you've configured it manually then yes, you need to delete the files you mentioned but you will also need to edit your 'hosts' file and remove the proxy entries from there.

**Comment by sukuraumono** [comment]
thanks, i found my mistake in saving hosts file. and now i finally succeeded.

**Comment by belldandu** [comment]
@sukuraumono you should close this issue then since @acffordyce973 was able to help you solve your issue.
