### ISSUE TITLE
pso2 authenticating sega id ISSUE still 

### ISSUE THREAD

**Issue by brobrobro187** [cyberkitsune/PSO2Proxy#189]
tryed doing all the steps on your WIKI. 

The only odd thing is the part: In command prompt, run ping cloud02.cyberkitsune.net, then ping gs001.pso2gs.net and check the results.

ping cloud02.cyberkitsune.net 

It Fails everytime. I played pso2 with the tweaker for a few weeks with no issues, and out of the blue this nightmare has started and not stopped. I have spend 2 days on this and i think i pulled all my hair out :(

**Comment by brobrobro187** [comment]
I just read someone saying to "Check your files in PSO2Tweaker. The arks layer installer leaves you a version behind."

But im not sure what that means.

**Comment by alama** [comment]
Ok, I going to point you to IRC support chat room, irc://irc.rustedlogic.net/#PSO2Proxypublic (no IRC client?  http://widget.mibbit.com/?server=irc.rustedlogic.net&channel=%23PSO2Proxypublic)
This for forum is for the support of the proxy software, NOT of the public proxy

**Comment by acffordyce973** [comment]
Yea, come to our IRC channel as @alama said above.

**Comment by brobrobro187** [comment]
I gave up and deleted the game. If i ever feel like wasting my time with another SEGA game i will let you know. Thanks for your offer though 😁
