### ISSUE TITLE
Retrieve current player's character name?

### ISSUE THREAD

**Issue by YielShelion** [cyberkitsune/PSO2Proxy#190]
I modified your proxy for personal use and I need to retrieve current character name to be listed in !clients. How do I do this?

**Comment by alama** [comment]
Realy, With what changes? ANYWAYS;
And to get the current character name, you getting to have dump and decode the packets used at Character Select screen?

**Comment by YielShelion** [comment]
I connected the proxy with a Telegram bot account so I can use commands and chat via telegram.
Currently global chat connection to telegram group, etc.
Now I am trying to implement "!clients" to work via telegram chat.
The original !clients command lists all data from all connected clients, such as IP, SEGA ID, user ID, block and such.
It works for me now via telegram chat but I just want to add additional info like current client's character name, and other info like level if possible.

Is there any other options though? Other than dumping the packets.

**Comment by alama** [comment]
No, we do not have any code to parse the char select screen data and keep it with the player connection object.

The only data useful to humans was/are the playerid and segaid from the SEGAID login packet, because it useful to add to the ban/whitelist lists.
