### ISSUE TITLE
Proxy error, dont know what to do

### ISSUE THREAD

**Issue by nugiedragon** [cyberkitsune/PSO2Proxy#191]
![error need help](https://cloud.githubusercontent.com/assets/20715669/17235748/b40858a4-556d-11e6-9a12-e96ffbc01e64.png)

**Comment by TheCrimsonDevil** [comment]
Make sure you have .NET 4.5 installed, and please post a link to your
logfile.txt.

**Comment by acffordyce973** [comment]
This issue section is for the PSO2Proxy software only. Client connection issues, particularly for another piece of software (Tweaker), should be taken to our IRC channel.
irc://irc.badnik.zone/#PSO2Proxypublic
Or if you don't have a client: http://widget.mibbit.com/?server=irc.badnik.zone&channel=%23PSO2Proxypublic
