### ISSUE TITLE
GIRC Users capable of opening a message box in-game

### ISSUE THREAD

**Issue by acffordyce973** [cyberkitsune/PSO2Proxy#192]
By prefixing an IRC message with special characters ("👉 👌" in our tests) a GIRC user is capable of opening a message box and displaying a message to users who have global chat enabled. This is an abusable bug which is capable of stopping player movement when the message box appears and should be looked into asap.
IRC Message example: 👉 👌 This is a test.
Images: http://i.imgur.com/UzXQtMy.jpg http://i.imgur.com/AcmBQ0R.jpg

**Comment by acffordyce973** [comment]
@alama might be able to take a look.

**Comment by acffordyce973** [comment]
Apparently as long as the IRC message contains the characters at any point it'll send it as a message box to in-game users.

**Comment by acffordyce973** [comment]
Also seems to be limited to system chat mode only.

**Comment by cyberkitsune** [comment]
This is likely due to the fact that those unicode characters as bytes are control codes for the message packet. We could potentially limited the character scope to filter out any weird characters?

**Comment by alama** [comment]
https://github.com/alama/PSO2Proxy/commit/e2d53911036e4c90fe4b4c80a2bb1631f0672985

**Comment by alama** [comment]
Why close this? the issue is that a gchat system message with some "funny" unicode bytes trigger this bug, we need to check the unicode table or have some code to filter out by byte and still have 'clear" unicode string
