### ISSUE TITLE
Cannot move to the new battle blocks

### ISSUE THREAD

**Issue by HunterGraubard** [cyberkitsune/PSO2Proxy#206]
Attempting to move to a battle block fails. Could we get a fix for this please?

**Comment by frkami123** [comment]
this could be fix by open a few certain ports but disconnect when join pvp game.

**Comment by noviarrs** [comment]
help... how to edit script move to the new battle blocks auto disconnect when join pvp game.. idk port and address battleship :3

**Comment by cyberkitsune** [comment]
closing pending protocol changes
