### ISSUE TITLE
Command Ban and Unban error?

### ISSUE THREAD

**Issue by KinaiPCP** [cyberkitsune/PSO2Proxy#211]
when I use the command (ban or unban) always displays the wrong command.

**Comment by KinaiPCP** [comment]
Oh rip... this is wrong params...
!ban segaid <Segaid> lel i think !ban <segaid> <value> xD

**Comment by tessar9070** [comment]
ah maaf saya jarang membuka email. dan ini maksut dari ban itu apa ?
2017-10-04 20:33 GMT+07:00 Kinai <notifications@github.com>:
