### ISSUE TITLE
Every commands is not working in PSO2

### ISSUE THREAD

**Issue by gesori-pro** [cyberkitsune/PSO2Proxy#219]
![image](https://user-images.githubusercontent.com/29522474/89109774-4910e300-d47f-11ea-8220-2a7b2516492a.png)
![image](https://user-images.githubusercontent.com/29522474/89109803-7bbadb80-d47f-11ea-912e-0a454a9aae96.png)
Every commands is not working in PSO2 now
I tried to use commands in Proxy Consoles
What should I do?

**Comment by cyberkitsune** [comment]
Hey I saw you closed this bug, did you resolve your issue?

**Comment by gesori-pro** [comment]
> 
> 
> Hey I saw you closed this bug, did you resolve your issue?

oh sorry for late reply yeah I solved this one but when I using G chat, it's showing like first picture.
but atleaset that command is works
